# Generated by Django 5.2.7 on 2025-11-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contributor",
            name="role",
        ),
        migrations.AddField(
            model_name="project",
            name="type",
            field=models.CharField(
                choices=[
                    ("back-end", "Back-end"),
                    ("front-end", "Front-end"),
                    ("iOS", "iOS"),
                    ("Android", "Android"),
                ],
                default="back-end",
                max_length=20,
            ),
        ),
    ]
